export default {
  popular_Funds: 'Popular Funds',
  taxSaving: 'Tax Saving',
  largeCap: 'Large and Multi Cap',
  smallCap: 'Small and Mid Cap',
  balancedFunds: 'Balanced Funds',
  NFO: 'NFO',
  funds: 'UNDS',
  goldFunds: 'Gold Funds',
  collection: 'Collections',
  empty_portfolio: 'Empty portfolio !',
  you_dont_have_any_investment: ' You dont have any investment',
  start_Investing: 'Start Investing',
  your_ZF_Expert: 'Your ZF Expert',
  zFUNDS_TEAM: 'ZFUNDS TEAM',
  planning: ' Retirement_Planning | Financial_Planning | Goal_Planning',
  call_advisor: 'Call Advisor',
  whatsapp_advisor: 'WhatsApp Advisor',
  your_acc: 'Your Account',
  help_support: 'Help and Support',
  about_zfunds: 'About ZFunds',
  first_year: '1 yr Return',
  second_year: '3 yr Return',
  third_year: '5 yr Return',
  See_all_funds: 'See all funds',
  logout: 'Logout',
};
